baseurl = "https://maruflmood.it"
metaDataFormat = "yaml"
title = "MaruflMood"
theme = "blist"

googleAnalytics: G-6942LKLMPR
enableRobotsTXT: true

DefaultContentLanguage = "it"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "I dream of sharing all this with someone."
      introSubtitle = "I dream of losing myself in colors, sounds and fragrances of the world. I dream of becoming a digital nomad and not to miss any sunset sea view."
      introPhoto = "/images/me.jpg"
      logo = "/images/logo.png"
    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1
    [[languages.en.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 2
    [[languages.en.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3
    [languages.en.params.homepage.social]
      # Global params common for both languages
      title = ""
      description = "You can find me here too"
      instagram = "https://instagram.com/maruflmood?igshid=YmMyMTA2M2Y="
      tripadvisor = "https://www.tripadvisor.it/Profile/maruflmood"
      tiktok = "https://www.tiktok.com/@maruflmood?_t=8XWE5XQZ9Tq&_r=1"
      email = "mailto:info@maruflmood.it"

  [languages.it]
    contentDir = "content/it" #Italiano
    weight = 2
    languageName = "Italiano"
    [languages.it.params]
      introTitle = "Sogno di condividere tutto questo con qualcuno."
      introSubtitle = "Sogno di perdermi nei colori, nei suoni e nei profumi del mondo. Sogno di diventare nomade digitale e non perdermi nessun tramonto vista mare."
      introPhoto = "/images/me.jpg"
      logo = "/images/logo.png"
    [[languages.it.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.it.menu.main]]
        name = "Chi sono"
        url = "page/about/"
        weight = 2

    [[languages.it.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3
    [languages.it.params.homepage.social]
      # Global params common for both languages
      title = ""
      description = "Puoi trovarmi anche qui"
      instagram = "https://instagram.com/maruflmood?igshid=YmMyMTA2M2Y="
      tripadvisor = "https://www.tripadvisor.it/Profile/maruflmood"
      tiktok = "https://www.tiktok.com/@maruflmood?_t=8XWE5XQZ9Tq&_r=1"
      email = "mailto:info@maruflmood.it"
  
  [languages.es]
    contentDir = "content/es" #Spagnolo
    weight = 3
    languageName = "Español"
    [languages.es.params]
      introTitle = "Sueño con compartir todo esto con alguien."
      introSubtitle = "Sueño con perderme en los colores, los sonidos y los aromas del mundo. Sueño con convertirme en una nómada digital y no perderme ningún atardecer frente al mar."
      introPhoto = "/images/me.jpg"
      logo = "/images/logo.png"
    [[languages.es.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.es.menu.main]]
        name = "Quien soy"
        url = "page/about/"
        weight = 2

    [[languages.es.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3
    [languages.es.params.homepage.social]
      # Global params common for both languages
      title = ""
      description = "Puedes encontrarme aquí también"
      instagram = "https://instagram.com/maruflmood?igshid=YmMyMTA2M2Y="
      tripadvisor = "https://www.tripadvisor.it/Profile/maruflmood"
      tiktok = "https://www.tiktok.com/@maruflmood?_t=8XWE5XQZ9Tq&_r=1"
      email = "mailto:info@maruflmood.it"

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2022 - Maruflmood · All rights reserved"
  favicon = "/images/logo.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = true

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

[params.homepage.social]
  # Global params common for both languages
  title = "Follow me"
  description = "I work on everything coding and tweet developer memes"
  twitter = "https://twitter.com/"
  linkedin = "https://linkedin.com/in/"
  xing = "https://www.xing.com/profile/"
  github = "https://github.com/"
  medium = "https://medium.com/"
  reddit = "https://reddit.com/"
  dribbble = "https://dribbble.com/"
  stackoverflow = "https://stackoverflow.com/"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
